name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    env:
      platform: aws
      username: ${{secrets.USERNAME}}
      password: ${{secrets.PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - name: "Mostrando variables de entorno"
        run: |
          echo "platform: ${{env.platform}}"
      - name: "Ejecutando condicional"
        if: env.platform != 'azure'
        run: echo "Platform is not azure"
      - name: "Mostrando variables por defecto y sistemas operativos"
        run: |
          echo "OS: $RUNNER_OS"
          echo "OS's are Windows, macOS, Linux"
      - name: Conditional to check repository secrets
        if: ${{env.username != '' && env.password != ''}}
        run: |
          echo "Hay un usuario con contraseña"
  job2:
    runs-on: ubuntu-latest
    outputs:
      salida1: ${{steps.mundo.outputs.test}}
      salida2: ${{steps.planeta.outputs.test1}}
      salida3: ${{steps.planeta.outputs.text1}}
    steps:
      - id: mundo
        run: echo "test=holaMundo" > "$GITHUB_OUTPUT"
      - id: planeta
        run: |
          echo "test1=holaPlaneta" >> "$GITHUB_OUTPUT"
          echo "text1=comoEstas" >> "$GITHUB_OUTPUT"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: OUTPUTS yes!
        env:
          SALIDA1: ${{needs.job2.outputs.salida1}}
          SALIDA2: ${{needs.job2.outputs.salida2}}
          SALIDA3: ${{needs.job2.outputs.salida3}}
        run: |
          echo "$SALIDA1"
          echo "$SALIDA2, $SALIDA3"
