name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    env:
      platform: aws
    runs-on: ubuntu-latest
    steps:
      - name: "Mostrando variables de entorno"
        run: |
          echo "platform: ${{env.platform}}"
      - name: "Ejecutando condicional"
        if: env.platform != 'azure'
        run: echo "Platform is not azure"
      - name: "Mostrando variables por defecto"
        run: |
          echo "OS: $RUNNER_OS"
          echo "OS's are Windows, macOS, Linux"
  job2:
    runs-on: ubuntu-latest
    outputs:
      salida2: ${{steps.planeta.outputs.test1}}
      salida1: ${{steps.mundo.outputs.test1}}
    steps:
      - id: mundo
        run: echo "test1=holaMundo" >> "$GITHUB_OUTPUT"
      - id: planeta
        run: echo "test1=holaPlaneta" >> "$GITHUB_OUTPUT"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - env:
          SALIDA1: ${{needs.job2.outputs.salida1}}
          SALIDA2: ${{needs.job2.outputs.salida2}}
        run: |
          echo "$SALIDA1"
          echo "$SALIDA2"