name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 1234567890123

    runs-on: ubuntu-latest
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola Mundo"
      - name: "Mostrar directorio"
        run: ls -a
      - name: "Mostrando variables de entorno"
        run: |
          echo "Leyendo las variables dentro del JOB"
          echo "platform: ${{env.platform}}"
          echo "region: ${{env.region}}"
          echo "account: ${{env.account}}"
