name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    env:
      platform: aws
    runs-on: ubuntu-latest
    steps:
      - name: "Mostrando variables de entorno"
        run: |
          echo "platform: ${{env.platform}}"
      - name: "Ejecutando condicional"
        if: env.platform != 'azure'
        run: echo "Platform is not azure"
      - name: "Mostrando variables por defecto"
        run: |
          echo "OS: $RUNNER_OS"
          echo "OS's are Windows, macOS, Linux"
  job2:
    runs-on: ubuntu-latest
    outputs:
      salida1: ${{steps.mundo.outputs.test1}}
      salida2: ${{steps.planeta.outputs.test1}}
      salida3: ${{steps.planeta.outputs.test2}}
    steps:
      - id: mundo
        run: echo "test1=holaMundo" >> "$GITHUB_OUTPUT"
      - id: planeta
        run: echo "test2=holaPlaneta" >> "$GITHUB_OUTPUT"
      - name: print outputs
        run: echo "$GITHUB_OUTPUT"