name: CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 1234567890123

    runs-on: ubuntu-latest
    steps:
      - name: "Mostrar mensaje"
        run: echo "Hola Mundo"
      - name: "Mostrar directorio"
        run: ls -a
      - name: "Mostrando variables de entorno"
        run: |
          echo "Leyendo las variables dentro del JOB"
          echo "platform: ${{env.platform}}"
          echo "region: ${{env.region}}"
          echo "account: ${{env.account}}"
      - name: "Ejecutando condicional"
        if: env.platform != 'azure'
        run: echo "Platform azure"
      - name: "Mostrando variables por defecto"
        run: |
          echo "API Url: $GITHUB_API_URL"
          echo "actor: ${{github.actor}}"
          echo "env: ${{github.env}}"
  if-Windows-else:
    runs-on: macos-latest
    steps:
      - name: condition 1
        if: runner.os == 'Windows'
        run: echo "The operating system on the runner is $env:RUNNER_OS."
      - name: condition 2
        if: runner.os != 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS."
